[WIP] fix: Show only hacktoberfest topic related issues
damcclean/hacktoberfest-finder pull request #205
Opened 2020-10-08 06:03 UTC by Kalovelo

This PR filters the fetched issues by topic (should be hacktoberfest).

Resolves #203 

The most **efficient** solution would be to use GraphQL queries to filter those issues. However, the graphql API needs authentication. 
The `search/issues` route does not provide a way to filters issues by topic. Therefore, the only way without passing the fetching rate limit was with 2 fetching queries each time.
1. The first one fetches all the hacktoberfest topic related repos
2. The second one (the original fetch) fetches all issues based on the user's preference (language/etc).

Both fetching queries fetch at their maximum data (`per_page=100`). 

Finally, those 2 results are compared, and only the issues (2nd fetch) with an existing `repository_url` in the repos data (1st fetch)  are shown.

Sadly, due to api unauthorized limits, I didn't find a more efficient way to implement, and I believe that the (authorized) Graphql option would work nicer.

2020-10-08 07:18 UTC, damcclean commented
Thanks for the pull request! I'll review it this evening after work. 

If we were to go down the route with authorisation, what would that need from me, just creating a Github key?

2020-10-08 15:41 UTC, Kalovelo commented
> If we were to go down the route with authorisation, what would that need from me, just creating a Github key?

I am currently working on changing the fetching from REST to GraphQL :tada:

I will set `.env` variable for the github token

2020-10-08 16:42 UTC, damcclean commented
> > If we were to go down the route with authorisation, what would that need from me, just creating a Github key?
> 
> I am currently working on changing the fetching from REST to GraphQL 🎉
> 
> I will set `.env` variable for the github token

Awesome, we may also need to add a step to the `README.md` file so that new developers coming to the project know that they'll need to generate a key as part of the setup.

2020-10-08 18:35 UTC, Kalovelo commented
PR updated, the fetching is done with Graphql :tada:

Issues are now topic related, and a github bearer token is required to make it work.

*The rate limit of GraphQL can be found [here](https://docs.github.com/en/free-pro-team@latest/graphql/overview/resource-limitations).

2020-10-08 19:50 UTC, damcclean requested changes
I've left some comments below. I'll have to check this out again tomorrow or during the weekend to ensure everything works with a valid Github key, as I can't confirm it with Netlify.

2020-10-08 19:50 UTC, damcclean commented on secrets.key.js
> +  // https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token
Could you remove this comment here, where to enter the key is already explained in the readme?

2020-10-08 19:50 UTC, damcclean commented on src/js/app.js
> +import secrets from '../../secrets.key';
A small nitpick of mine, could you remove the `;` at the ends of the lines?

2020-10-08 19:50 UTC, damcclean commented on src/js/app.js
> +        async getIssues(){
Another nitpick (sorry): could you leave a one line gap in between each of these methods please?

2020-10-08 19:50 UTC, damcclean commented on src/js/app.js
> +            const repos = data.data.search.repos.filter(({repo})=>repo.issues.issuesAll.length>0);
Could you mind making this line a little more readable, like this:

```js
const repos = data.data.search.repos.filter((repo) => {
    return repo.issues.issuesAll.length > 0
})
```

2020-10-08 21:23 UTC, damcclean commented
Looks good, thanks for the follow-up commit. I'll do some final testing tomorrow or during the weekend and get it merged. Thanks for your work on this one!

2020-10-10 12:02 UTC, merged

2020-10-10 12:03 UTC, damcclean commented
I've merged this PR in, made a little change to store the key in an `.env` file instead. Have a nice day :)

2020-10-10 13:02 UTC, Kalovelo commented
Sweet. you too @damcclean !