Top languages
damcclean/hacktoberfest-finder pull request #211
Opened 2020-10-18 13:11 UTC by xeBuz

Updated the list of languages, to get the most relevants on top. The list was taken from an older version from this repository

![image](https://user-images.githubusercontent.com/662916/96368434-19a37580-1154-11eb-92e6-481c306211f7.png)

2020-10-18 14:19 UTC, damcclean requested changes
Thanks for your pull request! I've left a few comments, if you wouldn't mind having a look over them, that would be great.

One tiny thing I noticed is that when you load the page initially, it looks a little differently than it should.

**This branch**
![image](https://user-images.githubusercontent.com/19637309/96370246-16f55000-1155-11eb-8020-ed4d32211cc0.png)

**The current version (master)**
![image](https://user-images.githubusercontent.com/19637309/96370274-2e343d80-1155-11eb-80ec-e1d882394669.png)
Also note how the load more button doesn't display on the current version.

Hopefully that's something nice and easy you could fix. Thanks again for the PR!

2020-10-18 14:19 UTC, damcclean commented on index.html
> +                              <option selected value="any">Any language</option>
Would you mind reverting the indentation on this element please?

2020-10-18 14:19 UTC, damcclean commented on src/js/app.js
>                  if (this.selectedSort==='noReplies')
I know this isn't your fault but would you mind adding a `{` to the end of this line and do the same sort of thing for the else statement, so it's like this

```js
if (whatever === 'something') {
    console.log('whatever is something')
} else {
    console.log('whatever is not something')
}
```

2020-10-18 14:37 UTC, xeBuz commented
> 
> One tiny thing I noticed is that when you load the page initially, it looks a little differently than it should.
> 
> Also note how the load more button doesn't display on the current version.
> 
> Hopefully that's something nice and easy you could fix. Thanks again for the PR!

This is weird, I can't get the same behaviour using the deploy preview version: https://deploy-preview-211--hacktoberfest-finder.netlify.app/

2020-10-18 14:38 UTC, damcclean commented
> > One tiny thing I noticed is that when you load the page initially, it looks a little differently than it should.
> > Also note how the load more button doesn't display on the current version.
> > Hopefully that's something nice and easy you could fix. Thanks again for the PR!
> 
> This is weird, I can't get the same behaviour using the deploy preview version: https://deploy-preview-211--hacktoberfest-finder.netlify.app/

That's strange, that's where I'm seeing it. I'm using Chrome if that makes any difference.

2020-10-18 14:39 UTC, damcclean commented
The other weird thing is that it doesn't look like you've touched anything that would affect it...

2020-10-18 14:41 UTC, damcclean requested changes

2020-10-18 14:41 UTC, damcclean commented on index.html
> +
Sorry to be really pernickety, could you remove the whitespace either side of the first and last elements in this `select` element? 

(sorry)

2020-10-18 14:52 UTC, damcclean commented
Thanks for the change! I'll try and remember to pull down later so I can see if the weird lazy loading issues happen locally.

2020-10-24 11:06 UTC, xeBuz commented
@damcclean is there anything I can do here?

2020-10-24 19:36 UTC, damcclean commented
> @damcclean is there anything I can do here?

Ah, sorry! Must have forgotten about this PR. I don't think there's anything you need to do 😂

2020-10-24 19:41 UTC, damcclean commented
> @damcclean is there anything I can do here?

Ahhh, sorry, must have forgotten about this pull request! I've just cloned this pull request down locally and recompiled the assets and I'm still seeing the same issue with the lazy loading stuff. 

Would you mind trying to reproduce it again and have a look at fixing it? If it's affecting the load more button too, maybe its a JavaScript thing rather than something to do with the HTML/CSS.

2020-10-28 21:38 UTC, damcclean commented
I'm going to merge this pull request now. We can fix that lazy loading bug another time. 

Thanks for your hard work and sorry for the long wait to get this merged.

2020-10-28 21:38 UTC, merged